language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
install:
    - pip install -q Django==$DJANGO --use-mirrors
    - if [[ $TRAVIS_PYTHON_VERSION != 3.3 || $TRAVIS_PYTHON_VERSION != 3.4 ]]; then pip install fabric unittest2 --use-mirrors ; fi
    - pip install colorama --use-mirrors
    - pip install coveralls --use-mirrors
    - pip install nose --use-mirrors
    - pip install future --use-mirrors
    - pip install six --use-mirrors
script:
    - python setup.py build
    - python setup.py sdist
    - nosetests -v --with-coverage --cover-package=color_printer --cover-tests --cover-erase --with-doctest
after_success:
    - coveralls
notifications:
    email: false